version: '3.0'
networks:
  anv_net:
    external: true
services:
    db:
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
            - "3306:3306"
        #volumes:
        #    - /home/nminhtuan/docker/volume/mysql:/mariadb/data
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
        stdin_open: true
        tty: true
        networks:
            - anv_net

    tca:
        image: tca
        container_name: tca
        restart: always
        ports:
            - "1099:1099"
            - "8101:8101"
            - "44444:44444"
            - "5005:5005"
            - "8181:8181"
        environment:
            - DB_URL=jdbc:mariadb://db:3306/tca
            - DB_USER=root
            - DB_PASS=mysql
            - DEBUG=true
        stdin_open: true
        tty: true
        depends_on:
            - db
        networks:
            - anv_net