version: '3.0'
networks:
  anv_net:
    external: true
services:
    db:
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
            - "3306:3306"
        # volumes:
            # - /home/nqloc/docker-mapping/mysql:/mariadb/data
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
        stdin_open: true
        tty: true
        networks:
            - anv_net

    # booking:
        # image: booking
        # container_name: booking
        # restart: always
        # environment:
            # - DB_URL=url
            # - DB_USER=root
            # - DB_PASS=mysql
        # stdin_open: true
        # tty: true
        # networks:
            # - anv_net